# Generated by Django 4.2.7 on 2025-07-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContextEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The actual content of the context entry"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("notes", "Notes"),
                            ("calendar", "Calendar"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_insights",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="AI-generated insights from context analysis",
                    ),
                ),
                (
                    "extracted_tasks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tasks extracted from context by AI",
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="Sentiment analysis score (-1 to 1)",
                        null=True,
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Keywords extracted from context",
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Context Entry",
                "verbose_name_plural": "Context Entries",
                "ordering": ["-timestamp"],
            },
        ),
    ]
